#!/usr/bin/env bash
# data/schools/*.json 을 data/snapshot.js 하나로 묶는다.
# file:// 에서는 fetch가 차단되므로 앱은 이 번들을 로드한다.
set -euo pipefail

cd "$(dirname "$0")/.."

OUT="data/snapshot.js"
VERSION="$(date +%Y-%m-%d)"
COUNT=0

{
  echo "// GENERATED by scripts/build-snapshot.sh — 직접 편집하지 말 것"
  echo "// 정본은 data/schools/*.json 입니다."
  echo "window.PM = window.PM || {};"
  echo "window.PM.SNAPSHOT = {"
  echo "  \"dataVersion\": \"$VERSION\","
  echo "  \"schools\": ["

  first=1
  for f in data/schools/*.json; do
    [ -e "$f" ] || continue
    if [ "$first" -eq 0 ]; then echo ","; fi
    first=0
    cat "$f"
    COUNT=$((COUNT + 1))
  done

  echo ""
  echo "  ]"
  echo "};"
} > "$OUT"

echo "wrote $OUT ($COUNT schools, version $VERSION)"
